name: docs-verify
on:
  workflow_call:

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - uses: actions/download-artifact@v4
      - run: pnpm install
      - run: pnpm build
