name: pnpm-update-snapshots
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node_version:
        type: string
        required: false
        default: '[16, 18, 20]'
      pnpm_version:
        type: string
        required: false
        default: 7.16.1
      update_snapshots:
        type: boolean
        required: false
        default: false
jobs:
  update_snapshots:
    if: ${{ inputs.update_snapshots  }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
        node-version: ${{ fromJson(inputs.node_version) }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ inputs.pnpm_version }}
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install
      - name: Update Snapshots
        run: pnpm update_snapshots
      - run: git commit -am "Update Snapshots"
      - run: git push
